spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      datasource:
        master:
          url: ${java668.mysql.host}/test?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
          username: ${java668.mysql.username}
          password: ${java668.mysql.password}
          driver-class-name: com.mysql.jdbc.Driver
          initialSize: 5
          minIdle: 5
          maxActive: 500
